version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jk-tech-db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=jk-tech-db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data: